# Generated by Django 5.2.1 on 2025-09-04 02:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(help_text="Nombre único de la categoría (ej: 'Guitarras eléctricas')", max_length=150, unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción detallada de la categoría', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación automática al guardar')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercio', models.CharField(help_text='Nombre de fantasía del comercio', max_length=160)),
                ('razon_social', models.CharField(help_text='Razón social o nombre legal del comercio', max_length=250, unique=True)),
                ('email', models.EmailField(help_text='Correo electrónico válido corporativo para el comercio', max_length=80)),
                ('telefono', models.CharField(help_text='Número de contacto en formato +56912345678', max_length=20)),
            ],
            options={
                'verbose_name': 'Comercio',
                'verbose_name_plural': 'Comercios',
                'ordering': ['nombre_comercio'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código único de identificación del producto', max_length=80, unique=True)),
                ('codigo_barra', models.CharField(help_text='Código de barras escaneable', max_length=150, unique=True)),
                ('nombre_producto', models.CharField(help_text='Nombre descriptivo del producto', max_length=150, unique=True)),
                ('nombre_abreviado', models.CharField(help_text='Nombre corto para tickets/facturas', max_length=80, unique=True)),
                ('descripcion', models.CharField(help_text='Detalles adicionales del producto', max_length=250)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario en moneda local', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('disponible', models.BooleanField(default=True, help_text='Disponibilidad del producto')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa del producto', null=True, upload_to='files_storage/productos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación automática al guardar')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización automática al modificar')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercio.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria__nombre_categoria', 'nombre_producto'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(help_text='Nombre referencial o identificatorio de la sucursal ', max_length=80, unique=True)),
                ('email', models.EmailField(help_text='Correo electrónico válido corporativo para la sucursal', max_length=80)),
                ('telefono', models.CharField(help_text='Número de contacto en formato +56912345678', max_length=20)),
                ('direccion', models.CharField(help_text='Dirección de la sucursal', max_length=250)),
                ('es_casa_matriz', models.BooleanField(default=False, help_text='Indica si la sucursal es casa matriz o no', verbose_name='Casa Matriz')),
                ('esta_asignada', models.BooleanField(default=False, help_text='Indica si la sucursal está asignada o no', verbose_name='Asignada')),
                ('estado', models.BooleanField(default=True, help_text='Indica si la sucursal está activa o no', verbose_name='Activa')),
                ('comercio', models.ForeignKey(help_text='Comercio que lidera el conjunto de sucursales', on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='comercio.comercio')),
                ('comuna', models.ForeignKey(help_text='Comuna de la dirección de la sucursal', on_delete=django.db.models.deletion.PROTECT, related_name='comuna', to='usuarios.comuna')),
                ('jefe_asignado', models.OneToOneField(blank=True, help_text='Jefe de local al cual se le asigna la sucursal', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['-es_casa_matriz', 'nombre_sucursal'],
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bodega', models.CharField(help_text='Indica el nombre de la bodega', max_length=80, unique=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si la bodega corresponde a la bodega principal', verbose_name='Es principal')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas', to='comercio.sucursal')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['sucursal__nombre_sucursal', '-es_principal', 'nombre_bodega'],
            },
        ),
        migrations.CreateModel(
            name='StockBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en esta bodega')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercio.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercio.producto')),
            ],
            options={
                'verbose_name': 'Stock en Bodega',
                'verbose_name_plural': 'Stocks en Bodegas',
                'unique_together': {('producto', 'bodega')},
            },
        ),
    ]
