# Generated by Django 5.2.1 on 2025-09-04 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
                'ordering': ['nombre_region'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Jefe de local', 'Jefe de local'), ('Cajero', 'Cajero')], help_text='Nombre identificador del rol (Administrador, Jefe de local o Cajero)', max_length=80, unique=True)),
                ('descripcion', models.CharField(help_text='Descripción detallada de las funciones asociadas al rol', max_length=250)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(max_length=80)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.region')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['nombre_comuna'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT en formato 12345678-9 (incluye guión y dígito verificador)', max_length=12, unique=True)),
                ('nombres', models.CharField(help_text='Nombres del usuario', max_length=80)),
                ('ap_paterno', models.CharField(help_text='Apellido paterno', max_length=80)),
                ('ap_materno', models.CharField(help_text='Apellido materno', max_length=80)),
                ('telefono', models.CharField(help_text='Número de contacto en formato +56912345678', max_length=20)),
                ('email', models.EmailField(help_text='Correo electrónico válido (será usado para notificaciones)', max_length=80)),
                ('direccion', models.CharField(help_text='Dirección completa: Calle, número, [depto/villa/población/bloque] (opcional)', max_length=250)),
                ('estado', models.BooleanField(default=True, help_text='Indica si el registro está activo o eliminado', verbose_name='Activo')),
                ('comuna', models.ForeignKey(blank=True, help_text='Comuna de la dirección del usuario (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.comuna')),
                ('rol', models.ForeignKey(help_text='Rol del usuario (Administrador, Jefe de local o Cliente)', on_delete=django.db.models.deletion.PROTECT, to='usuarios.rol')),
                ('usuario', models.OneToOneField(help_text='Usuario de autenticación asociado (auth.User)', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['rut', 'ap_paterno', 'ap_materno', 'nombres', 'usuario__last_name'],
            },
        ),
    ]
